# Generated by Django 2.0.7 on 2020-10-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0002_readdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readdetail',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ReadDetail',
        ),
    ]
