# Generated by Django 2.2.16 on 2020-10-06 15:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('read_statistic', '0003_auto_20201006_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnum',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType', verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='readnum',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='readnum',
            name='read_number',
            field=models.IntegerField(default=0, help_text='阅读数', verbose_name='阅读数'),
        ),
        migrations.CreateModel(
            name='ReadDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='时间')),
                ('read_number', models.IntegerField(default=0, verbose_name='阅读数量')),
                ('object_id', models.PositiveIntegerField(verbose_name='id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType', verbose_name='类型')),
            ],
        ),
    ]
