# Generated by Django 2.2.16 on 2020-10-08 13:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201006_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='博客内容', verbose_name='博客内容'),
        ),
    ]
