# Generated by Django 2.2.16 on 2020-10-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201011_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_face',
            field=models.URLField(default='https://i.loli.net/2020/10/31/x59ZwVgkvYSlMDn.jpg', verbose_name='封面'),
        ),
    ]
